---
driver:
  name: vagrant
  gui: true
  network:
    - ["forwarded_port", {guest: 8081, host: 8081}]
    - ["forwarded_port", {guest: 8082, host: 8082}]
    - ["forwarded_port", {guest: 8083, host: 8083}]
    - ["forwarded_port", {guest: 8989, host: 8989}]
    - ["private_network", {ip: "192.168.2.2"}]
  customize:
    audio: coreaudio
    audiocontroller: ac97
    vram: 32
    memory: 1024

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec
#   format: doc

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[ulimit]
      - recipe[mediacenter::kodi]
      - recipe[mediacenter::sabnzbdplus]
      - recipe[mediacenter::sonarr]
      - recipe[mediacenter::couchpotato]
    attributes: {
      mediacenter: {
        user: "kodi",
        group: "kodi"
      },
      sabnzbd: {
        user: "kodi",
        group: "kodi",
        listen_port: "8081"
      }
    }
