name 'mediacenter'
maintainer 'G. Arends'
maintainer_email 'gdarends@gmail.com'
license 'all_rights'
description 'Installs/Configures mediacenter'
long_description 'Installs/Configures mediacenter'
version '0.1.0'

depends 'apt'
depends 'kodi'
depends 'ulimit'
