name 'mediacenter'
maintainer 'G. Arends'
maintainer_email 'gdarends@gmail.com'
license 'all_rights'
description 'Installs/Configures mediacenter'
long_description 'Installs/Configures mediacenter'
version '0.1.0'

depends 'apt', '~> 4.0'
depends 'ulimit', '~> 0.5.0'
depends 'kodi', '~> 0.1.4'
depends 'poise-python', '~> 1.4.0'
